// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql_model

type Response interface {
	IsResponse()
}

type ResponseError struct {
	Field *string `json:"field"`
	Error string  `json:"error"`
}

type SignUpDto struct {
	Password string `json:"password"`
	Email    string `json:"email"`
}

type SignUpResponse struct {
	Errors    []*ResponseError `json:"errors"`
	TokenPair *TokenPair       `json:"tokenPair"`
}

func (SignUpResponse) IsResponse() {}

type TokenPair struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type User struct {
	UID      string  `json:"uid"`
	Email    string  `json:"email"`
	Name     *string `json:"name"`
	ImageURL *string `json:"imageURL"`
	Website  *string `json:"website"`
}

type UserResponse struct {
	Errors []*ResponseError `json:"errors"`
	User   *User            `json:"user"`
}

func (UserResponse) IsResponse() {}
